apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-app
spec:
  selector:
    matchLabels:
      app: aspnet-app
  template:
    metadata:
      labels:
        app: aspnet-app
    spec:
      containers:
      - name: aspnet-app
        image: vafzamora/aspnetapp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aspnet-app-svc
spec:
  selector:
    app: aspnet-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
